export const STRINGS = {
  ko: {
    onboarding: {
      tag: '✨ 같은 학교 · 같은 동네',
      title1: '근처 K-pop 팬을\n',
      titleHighlight: '지금 바로',
      title2: ' 찾아봐',
      desc: 'AI가 취향을 분석해 진짜 잘 맞는\n팬을 5분 안에 연결해드려요',
      btnStart: 'Get Started →',
      btnSignIn: 'Already have an account? Sign in',
    },
    signUp: {
      h1: '시작해볼까요? 👋',
      sub: '소셜 계정으로 5초 만에 가입 완료',
      promoTitle: '⚡ 가입 후 5분 안에',
      promoSub: '근처 K-pop 팬 매칭이 시작됩니다',
      apple: 'Apple로 계속하기',
      google: 'Google로 계속하기',
      email: '이메일로 가입',
      or: '또는',
      terms: '가입하면 ',
      tos: '이용약관',
      termsAnd: ' 및 ',
      pp: '개인정보처리방침',
      termsEnd: '에 동의하게 됩니다',
    },
    groups: {
      h1: '최애 그룹을 골라봐 💜',
      sub: '여러 개 선택 가능 · 나중에 수정 가능',
      empty: '아직 선택 안 했어요',
      countBoldSuffix: '개',
      countText: ' 선택됨 · 계속 추가 가능해요',
      next: '다음으로 →',
    },
    style: {
      h1: '팬 스타일이 뭐야? 🎵',
      sub: '나와 비슷한 팬을 매칭해드려요',
      next: '다음으로 →',
      fanStyleDescs: [
        '공연·팬미팅 같이 갈 동반자를 찾아요 🎫',
        '온라인 응원, 스트리밍, 투표 함께해요',
        '포카 교환, 굿즈 공동구매 같이 해요',
        '가볍게 K-pop 얘기 나눌 친구 원해요',
      ],
    },
    location: {
      h1: '마지막 단계!',
      desc1: '위치 권한을 허용하면\n',
      descHighlight: '반경 2km 이내',
      desc2: ' 팬을\n실시간으로 발견할 수 있어요',
      allow: '📡 위치 허용하고 시작!',
      skip: '나중에 설정할게요',
    },
    radar: {
      subtitle: '근처 K-pop 팬 탐색 중…',
      onlineSuffix: '명 온라인',
      centerLabel: '나',
      fanFound: '팬 발견',
      initToastMsg: '근처 K-pop 팬 탐색 시작!',
      radarCountPre: '반경 2km 내 ',
      radarCountSuf: '명 발견',
      filterAll: '🎵 전체',
      filterConcert: '🎪 콘서트 동행',
      notifTitle: '알림',
      notifMsg: '새 매칭 3건 도착!',
      profileTitle: '프로필',
      profileMsg: '내 프로필 보기',
    },
    match: {
      title: '💘 매칭',
      subtitle: 'AI 추천 · 실시간 업데이트',
      cardMeta: 'UCLA · 2학년 · 0.8km',
      interestTitle: '공통 관심사 5개',
      tagConcert: '🎫 콘서트',
      tagPokaExchange: '🃏 포카교환',
      tagFancam: '📸 직캠',
      swipeHint: '← 넘기기           좋아요 →',
      passTitle: '다음 매칭',
      passMsg: '새로운 팬을 찾고 있어요…',
      superTitle: '슈퍼 라이크!',
      superMsg: 'Sophie K.에게 알림이 갔어요',
      notifTitle: '알림',
      notifMsg: '새 매칭 3건 도착!',
      profileTitle: '프로필',
      profileMsg: '내 프로필 보기',
    },
    matched: {
      desc: 'Sophie K.도 나를 좋아해요!\nBTS 팬 동지를 찾았어요 💜\n',
      btnMsg: '💬 지금 메시지 보내기',
      btnBack: '레이더로 돌아가기',
    },
    chat: {
      matchIntroTitle: '🎊 새로운 매칭! 94% 호환',
      matchIntroSub: 'BTS, aespa 공통 팬 · 0.8km',
      placeholder: '메시지 입력…',
      timePeriod: '오후',
      suggestConcert: '🎫 같이 콘서트 가요!',
      suggestPoka: '🃏 포카 교환할래요?',
      suggestMeet: '☕ 캠퍼스에서 만나요',
      autoReply: '좋아요!! 언제가 좋아요? 😊',
      autoReplies: [
        '완전 좋아요! 🎉',
        '저도 그 생각 하고 있었어요!',
        '진짜요?? 대박 😆',
        '🎵 좋아요! 언제 시간 돼요?',
        '헐 너무 좋다!! 설레ㅠㅠ',
        '오 그거 저도 관심 있어요!',
      ],
      initMsgs: [
        { text: '안녕하세요! Fan Radar에서 매칭됐네요 ☺️ BTS 아미시죠?', type: 'rcv' as const, time: '오후 3:24' },
        { text: '네!! 아미예요 😊 혹시 다음달 콘서트 가세요?',             type: 'snt' as const, time: '오후 3:25' },
        { text: '헐 저도 티켓 있어요!! LA 공연이요? 같이 가요 🎫✨',       type: 'rcv' as const, time: '오후 3:26' },
        { text: '진짜요?? 완전 좋아요!! UCLA 다니세요?',                   type: 'snt' as const, time: '오후 3:27' },
        { text: '네 2학년이에요! 캠퍼스에서 만날 수 있겠다 🏫',            type: 'rcv' as const, time: '오후 3:27' },
      ],
    },
    alerts: {
      title: '🔔 알림',
      subtitle: '탭하면 읽음 처리돼요',
      markRead: '모두 읽음',
      empty: '새 알림이 없어요 🔔',
      items: [
        { icon: '💘', badge: '새 매칭',    title: 'Sophie K.와 매칭됐어요!',          body: 'BTS, aespa 공통 팬 · 94% 호환',     time: '2분 전',   read: false },
        { icon: '⭐', badge: '슈퍼 라이크', title: '누군가 슈퍼 라이크를 보냈어요!',  body: '프로필을 확인해보세요',              time: '15분 전',  read: false },
        { icon: '📡', badge: '근처 팬',    title: 'BTS 팬 3명이 근처에 있어요',       body: '반경 0.5km · 지금 온라인',          time: '1시간 전', read: false },
        { icon: '💬', badge: '새 메시지',  title: 'Sophie: 콘서트 같이 가요!',        body: '채팅방에서 확인하세요',              time: '2시간 전', read: true  },
        { icon: '🎤', badge: '이벤트',     title: '근처에 BTS 팝업스토어 오픈!',      body: '0.3km · 오늘 오후 2시까지',         time: '3시간 전', read: true  },
      ],
    },
    nav: {
      radar: '레이더',
      match: '매칭',
      notif: '알림',
      chat: '채팅',
      me: '나',
    },
    profile: {
      title: '👤 나',
      subtitle: '설정 및 환경설정',
      lang: '언어',
      notif: '알림',
      location: '위치',
      version: 'Fan Radar v1.0',
    },
  },

  en: {
    onboarding: {
      tag: '✨ Same School · Same Neighborhood',
      title1: 'Find K-pop Fans\n',
      titleHighlight: 'Right Now',
      title2: ' Nearby',
      desc: 'AI analyzes your taste to connect\nyou with the perfect fan in 5 min',
      btnStart: 'Get Started →',
      btnSignIn: 'Already have an account? Sign in',
    },
    signUp: {
      h1: "Let's Start! 👋",
      sub: 'Sign up in 5 seconds with social login',
      promoTitle: '⚡ Within 5 min of signing up',
      promoSub: 'Nearby K-pop fan matching begins',
      apple: 'Continue with Apple',
      google: 'Continue with Google',
      email: 'Sign up with Email',
      or: 'or',
      terms: 'By signing up, you agree to the ',
      tos: 'Terms of Service',
      termsAnd: ' and ',
      pp: 'Privacy Policy',
      termsEnd: '',
    },
    groups: {
      h1: 'Pick your fave group 💜',
      sub: 'Multiple allowed · Can change later',
      empty: 'Nothing selected yet',
      countBoldSuffix: '',
      countText: ' selected · Keep adding more',
      next: 'Next →',
    },
    style: {
      h1: 'What kind of fan are you? 🎵',
      sub: "We'll match you with similar fans",
      next: 'Next →',
      fanStyleDescs: [
        'Looking for a concert & fan meet buddy 🎫',
        'Online cheering, streaming & voting together',
        'Photocard trading & group merch buys',
        'Casual K-pop chat friends wanted',
      ],
    },
    location: {
      h1: 'Last step!',
      desc1: 'Allow location to discover fans\n',
      descHighlight: 'within 2km',
      desc2: ' in real time',
      allow: '📡 Allow & Start!',
      skip: 'Set up later',
    },
    radar: {
      subtitle: 'Scanning nearby K-pop fans…',
      onlineSuffix: ' online',
      centerLabel: 'Me',
      fanFound: 'fan found',
      initToastMsg: 'Scanning for nearby K-pop fans!',
      radarCountPre: '',
      radarCountSuf: ' fans found nearby',
      filterAll: '🎵 All',
      filterConcert: '🎪 Concert Buddy',
      notifTitle: 'Alerts',
      notifMsg: '3 new matches arrived!',
      profileTitle: 'Profile',
      profileMsg: 'View my profile',
    },
    match: {
      title: '💘 Match',
      subtitle: 'AI Picks · Live Updates',
      cardMeta: 'UCLA · Sophomore · 0.8km',
      interestTitle: '5 COMMON INTERESTS',
      tagConcert: '🎫 Concert',
      tagPokaExchange: '🃏 Photocard',
      tagFancam: '📸 Fancam',
      swipeHint: '← Pass              Like →',
      passTitle: 'Next Match',
      passMsg: 'Looking for new fans…',
      superTitle: 'Super Like!',
      superMsg: 'Sophie K. was notified',
      notifTitle: 'Alerts',
      notifMsg: '3 new matches arrived!',
      profileTitle: 'Profile',
      profileMsg: 'View my profile',
    },
    matched: {
      desc: 'Sophie K. likes you back!\nFound a BTS fan buddy 💜\n',
      btnMsg: '💬 Send a Message Now',
      btnBack: 'Back to Radar',
    },
    chat: {
      matchIntroTitle: '🎊 New Match! 94% Compatible',
      matchIntroSub: 'BTS, aespa common fan · 0.8km',
      placeholder: 'Message…',
      timePeriod: 'PM',
      suggestConcert: "🎫 Let's go to a concert!",
      suggestPoka: '🃏 Want to trade photocards?',
      suggestMeet: '☕ Meet on campus',
      autoReply: 'Sounds great!! When are you free? 😊',
      autoReplies: [
        'Love it! 🎉',
        'I was thinking the same thing!',
        "Really?? That's amazing 😆",
        '🎵 Sure! When are you free?',
        "Oh wow I'm so excited!!",
        "Oh I'm interested in that too!",
      ],
      initMsgs: [
        { text: "Hi! We matched on Fan Radar ☺️ You're a BTS ARMY right?", type: 'rcv' as const, time: 'PM 3:24' },
        { text: "Yes!! I'm ARMY 😊 Going to next month's concert?",          type: 'snt' as const, time: 'PM 3:25' },
        { text: "Oh I have tickets too!! The LA show? Let's go together 🎫✨", type: 'rcv' as const, time: 'PM 3:26' },
        { text: "Really?? That's awesome!! Do you go to UCLA?",              type: 'snt' as const, time: 'PM 3:27' },
        { text: 'Yes, sophomore! We could meet on campus 🏫',               type: 'rcv' as const, time: 'PM 3:27' },
      ],
    },
    alerts: {
      title: '🔔 Alerts',
      subtitle: 'Tap to mark as read',
      markRead: 'Mark all read',
      empty: 'No alerts yet 🔔',
      items: [
        { icon: '💘', badge: 'New Match',   title: "You matched with Sophie K.!",        body: 'BTS, aespa common fan · 94% compatible', time: '2m ago',  read: false },
        { icon: '⭐', badge: 'Super Like',  title: 'Someone super liked your profile!',  body: 'Check your profile',                      time: '15m ago', read: false },
        { icon: '📡', badge: 'Nearby Fans', title: '3 BTS fans spotted near you',        body: 'Within 0.5km · Online now',               time: '1h ago',  read: false },
        { icon: '💬', badge: 'Message',     title: "Sophie: Let's go to the concert!",   body: 'Check the chat',                          time: '2h ago',  read: true  },
        { icon: '🎤', badge: 'Event',       title: 'BTS pop-up store opening nearby!',   body: '0.3km · Until 2PM today',                 time: '3h ago',  read: true  },
      ],
    },
    nav: {
      radar: 'Radar',
      match: 'Match',
      notif: 'Alerts',
      chat: 'Chat',
      me: 'Me',
    },
    profile: {
      title: '👤 Me',
      subtitle: 'Settings & Preferences',
      lang: 'Language',
      notif: 'Notifications',
      location: 'Location',
      version: 'Fan Radar v1.0',
    },
  },
};
